### ISSUE TITLE
Libraries that depend on older versions of Clojure

### ISSUE THREAD

**Issue by theronic** [seancorfield/boot-tools-deps#14]
Hi @seancorfield. This is great, thanks

How do I deal with libraries that depend on e.g. Clojure 1.7 when the boot pod is running in Clojure 1.9? Would it be possible to recursively build each Git checkout lib using a separate boot process, to produce artifacts for linking?

**Comment by seancorfield** [comment]
As of release 0.2.3 that should "just work".  See the discussion in pull request #13 which makes that possible.
