### ISSUE TITLE
Transitive deps are added to the pom

### ISSUE THREAD

**Issue by moxaj** [seancorfield/boot-tools-deps#17]
It seems like my generated `pom.xml` has not only the dependencies I specified in `deps.edn`, but all their transitive dependencies as well. While technically this shouldn't matter, I'd prefer my `pom`s nice and clean.

To reproduce:

- add `org.clojure/clojurescript {:mvn/version "1.9.946"}` to your `deps.edn`
- `boot deps --overwrite-boot-deps pom target`
- check out the generated `pom.xml`; it should have extra transitive dependencies listed such as `google-closure-library`

**Comment by seancorfield** [comment]
This is due to how `tools.deps` itself works -- see the discussion in #7.
