### ISSUE TITLE
How to require git deps for libs that are used in build.boot?

### ISSUE THREAD

**Issue by theronic** [seancorfield/boot-tools-deps#18]
I need to use a fork of boot-react-native. I've added a :local/root path in deps.edn.

I see there is a `:quick-merge` argument. I tried to use it, but I don't know how.

How should I "bootstrap" dependencies that are required in the build.boot file which do not originate from Maven?

**Comment by seancorfield** [comment]
This is a support question, not an "issue". Ask in #tools-deps on Slack instead (and it will help offer you have the code in a repo somewhere that folks can look at).
