### ISSUE TITLE
Appears to ignore :exclusions in deps.edn coords

### ISSUE THREAD

**Issue by solussd** [seancorfield/boot-tools-deps#19]
If I add an :exclusions keyval in a dep coordinate boot-tools-deps appears to ignore it.

**Comment by seancorfield** [comment]
Please read the comments in #7 -- that is `tools.deps` and Maven/Aether, not `boot-tools-deps`.

**Comment by solussd** [comment]
Hmm, afaict the linked issue doesn't talk about exclusions. Could you give me a bit more context to help me understand?

Thanks!

**Comment by seancorfield** [comment]
`tools.deps` is the library that `boot-tools-deps` uses to process `deps.edn` files -- if `:exclusions` is being ignored, it's `tools.deps` that is ignoring it.

`boot-tools-deps` uses whatever comes back from `tools.deps` to add JARs to the classpath and directories to the resource/source paths.

If you tell `boot-tools-deps` to overwrite (`-B`) or merge (`-Q`) Boot's `:dependencies`, it uses the list of libraries that comes back from `tools.deps`. There is no additional processing beyond that.
