### ISSUE TITLE
deps task throws exception in most/many situations

### ISSUE THREAD

**Issue by drewverlee** [seancorfield/boot-tools-deps#22]
Given this project https://github.com/drewverlee/example-1

Run boot -h

I get an unexpected exception, of which this seems to be the relevent part:

java.lang.ClassCastException: java.lang.Character cannot be cast to java.util.Map$Entry.

**Comment by seancorfield** [comment]
Your use of `deps` with `:config-data` is incorrect. Look at the `-Sdeps` argument of `clj` -- that's what `:config-data` is: an EDN string that describes dependencies, for example:
```
(deps :config-data '{:deps {clj-time {:mvn/version "0.14.3"}}}' :quick-merge true)
```
The `deps.edn` file in the current folder is _always read_.
