### ISSUE TITLE
Issue with private repos and transitive dependencies

### ISSUE THREAD

**Issue by mattyulrich** [seancorfield/boot-tools-deps#24]
I'm having an issue with transitive dependencies in a corporate repo.  When I refer to my company dependencies that have transitive dependencies within the corporate repo (setting the repo in :mvn/repos within deps.edn), the 'deps' task seems to be trying to locate the transitive dependencies in clojars first.

Here's what happens when I do either 

`(boot (deps :overwrite-boot-deps true))`

or

`(boot (deps :quick-merge true))`

error:

`org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.xxx-masked-group:xxx-masked-artifact:jar:1.0.1 in clojars (https://repo.clojars.org/)`

I initially thought this was an issue with tools-deps, but I can run a repl with the 'clj' tool without a problem (clj tool builds a clean dependency tree and classpath).

Is this expected (a function of using the boot dependency resolution)?  It's funny because if I add those dependencies to the build.boot file rather than deps.edn, they are cleanly resolved.

**Comment by seancorfield** [comment]
`boot-tools-deps` doesn't currently pay any attention to the `:mvn/repos` key. That would be an interesting enhancement!

**Comment by mattyulrich** [comment]
Ahh - so do I just need to add `:repositories` to the build.boot file to mirror `:mvn/repos` in the deps.edn?

That's not bad - didn't even think to try that.

**Comment by seancorfield** [comment]
That should work, yes. Would be nice if it did that for you, eh?

**Comment by mattyulrich** [comment]
For reference, this worked fine!  I don't see this as being such a big deal, but it would be a cool feature.  I'm going to close this issue then.  Thanks for the help!  Have a great weekend!

**Comment by seancorfield** [comment]
Let me know if release 0.4.7 works (without duplicating the `:repositories` data) -- although I still don't think this will work with _transient_ dependencies (because that information is lost in the resolution process inside `tools.deps` itself).
