### ISSUE TITLE
How to use different classpath for each task in a pipeline

### ISSUE THREAD

**Issue by larkery** [seancorfield/boot-tools-deps#25]
Hi,

This might be impossible or wrong thinking on my part - I'm certainly not sure that it's a bug.
I have a program I'm building with boot that has a frontend in clojurescript and backend in clojure.

To build it I need to do clojurescript compilation for the frontend bits, and AOT + uberjar stuff for the backend bits.

The frontend build has different dependencies to the backend build, which are split by aliases in deps.edn.

What I have tried to do is write something like this

```
(deftask build-frontend []
   (comp (deps :aliases [:client]) (cljs)))

(deftask build-jar []
   (comp (build-frontend) (deps :aliases [:server] :overwrite-boot-deps true) (aot) (pom) (uber) (jar)))
```

However, as far as I can tell the effect of (deps) is not within task execution but in the construction of the task pipeline. What happens if I stick in a bunch of printlns and verbosity is:

1. `(deps :aliases [:client])` modifies the classpath to contain the client-side dependencies
2. `(deps :aliases [:server] :overwrite-boot-deps true)` zaps the classpath, throwing all that away
3. The other tasks get run; `(cljs)` fails because it can't resolve dependencies from the `:client` alias (the reason `cljs` exists at all is because I actually resolve its definition in the `deftask` before anything else happens, for other reasons)

Do you know if there is some voodoo I can do here to be able to say: make a pipeline of these tasks; run the first task with these dependencies and the second with these other dependencies.

Thank you for your work,

Tom

**Comment by larkery** [comment]
Following on with this I have read #1 which seemed like the right kind of thing.
I have defined my own task which is like

```
(deftask deps* [...]
   (boot/with-pre-wrap fs
      (load-deps ...)
      fs)))
```

This appears to run before the next task in the pipeline, but unfortunately the next task does not perceive the new dependencies as being on the classpath :/

**Comment by larkery** [comment]
Further reading of task source code shows that some tasks create a pod from the boot environment when they construct their middleware, and other tasks query the environment when the task evaluates.

For tasks of the first type it is necessary to do something like this:

```
(defmacro with-load-deps [args & body]
   (let [env# (boot/get-env)]
      (load-deps ~args)
      (let [result# (do ~@body)]
         (boot/set-env! env#) result#)))

(with-load-deps {:classpath-aliases [:foo]} (task))
```

For tasks of the second type, `deps*` as above does work.

A combined form should work in all cases

```
(defmacro with-load-deps [args & body]
  (let [aliases     (vec (:aliases args))
        add-aliases #(into aliases %)
        
        args (-> args
                 (update :class-path-aliases add-aliases)
                 (update :main-aliases add-aliases)
                 (update :resolve-aliases add-aliases)
                 (dissoc :aliases))]
    `(let [env# (boot/get-env)]
       (load-deps ~args)
       (let [result# (boot/with-pass-thru fs#
                       (load-deps ~args)
                       ~@body)]
         (boot/set-env! env#)
         result#))))
```

although it is arguably quite horrible.

I think I've answered my own question so feel free to close this unless there's a Right Answer that I am missing here.

**Comment by seancorfield** [comment]
Glad you've figured out a solution -- but you're operating far outside the design goals for `boot-tools-deps`: it was intended to let you wrap an existing, working `deps.edn` project with `boot` to perform certain common, simple Boot tasks. It was prior to the arrival of the ecosystem of tools built on `tools.deps`/`deps.edn` and was only a workaround for the lack of those tools. I probably ought to archive it at this point!
