### ISSUE TITLE
How to handle local and git deps?

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/boot-tools-deps#6]
`tools.deps(.alpha)` supports both local and git dependencies -- how should these work with `boot-tools-deps`?

**Comment by theronic** [comment]
Are `:git/url` deps not supported?

**Comment by theronic** [comment]
As per @seancorfield [via Slack](https://clojurians.slack.com/archives/C053K90BR/p1516898677000813):

> `boot-tools-deps` doesn't support Git _yet_ -- I've been holding off doing additional work on it until `tools.deps` stabilizes a bit (I think the last round of refactoring in `tools.deps` may have broken `boot-tools-deps` anyway). I'm hoping to spend this weekend bringing `boot-tools-deps` back up to the latest version and seeing how to make the Git stuff work. It'll be quite a change, I expect.
> 
> Part of the issue is the tension between how Boot handles dependencies and how `tools.deps` handles them. For example, `:scope` doesn't work as expected for transitive dependencies so you can end up with unexpected libraries on your classpath if you're trying to build a project, rather than just run it (since `clj` and `tools.deps` is about _running_ code, not _building_ projects).

**Comment by seancorfield** [comment]
Fixed in 0.2.0!
